import { z } from 'zod'

export const SettingCategory = z.enum(['models', 'navigation', 'device', 'toggles', 'steering', 'cruise', 'visuals', 'developer', 'other'])
export type SettingCategory = z.infer<typeof SettingCategory>

export type DeviceParam = {
  label: string
  description: string
  category: SettingCategory
  advanced?: boolean
  readonly?: boolean
  hidden?: boolean
  options?: { value: number; label: string }[]
  min?: number
  max?: number
  step?: number
}

export enum DeviceParamType {
  String = 0,
  Boolean = 1,
  SelectOrInt = 2,
  Number = 3,
  Date = 4,
  JSON = 5,
}

export const DEVICE_PARAMS = {
  // Navigation
  MapboxToken: { label: 'Mapbox Token', description: 'API token for Mapbox navigation', category: 'navigation' },
  MapboxRoute: { label: 'Current Route', description: 'Current navigation destination', category: 'navigation' },
  MapboxFavorites: { label: 'Favorites', description: 'Saved navigation destinations', category: 'navigation', hidden: true },
  AllowNavigation: { label: 'Allow Navigation', description: 'Enable navigation features', category: 'navigation' },
  NavDesiresAllowed: { label: 'Nav Desires', description: 'Allow navigation desires (tries to turn automatically)', category: 'navigation' },
  MapboxRecompute: { label: 'Recompute Route', description: 'Allow route recomputation (recomputes when off the selected route)', category: 'navigation' },
  MapboxSettings: { label: 'Mapbox Settings', description: 'Mapbox configuration', category: 'navigation', hidden: true },

  // Device
  DongleId: { label: 'Dongle ID', description: 'Unique device identifier', category: 'device', readonly: true },
  GitCommit: { label: 'Git Commit', description: 'Current software version', category: 'device', readonly: true },
  GithubSshKeys: { label: 'GitHub SSH Keys', description: 'SSH keys for GitHub access', category: 'device', hidden: true },
  GithubUsername: { label: 'GitHub Username', description: 'Connected GitHub account', category: 'device' },
  GsmMetered: { label: 'GSM Metered', description: 'Cellular data metering', category: 'device' },
  IsLdwEnabled: { label: 'LDW Enabled', description: 'Lane departure warnings', category: 'device' },
  IsMetric: { label: 'Metric Units', description: 'Display metric measurements', category: 'device' },
  LanguageSetting: { label: 'Language', description: 'UI language', category: 'device' },
  OpenpilotEnabledToggle: { label: 'sunnypilot Enabled', description: 'Master sunnypilot toggle', category: 'device' },
  RecordFront: { label: 'Record Front', description: 'Front camera recording', category: 'device' },
  IsRHD: { label: 'Right-Hand Drive', description: 'RHD vehicle configuration', category: 'device' },
  Version: { label: 'Version', description: 'Software version number', category: 'device', readonly: true },
  QuietMode: { label: 'Quiet Mode', description: 'Minimize sound notifications', category: 'device' },
  MaxTimeOffroad: { label: 'Max Time Offroad', description: 'Max idle time before shutdown', category: 'device', advanced: true },
  NetworkMetered: {
    label: 'Network Metered',
    description: 'Metered connection',
    category: 'device',
    advanced: true,
    hidden: true,
    options: [
      {
        value: 0,
        label: 'Default',
      },
      {
        value: 1,
        label: 'Metered',
      },
      {
        value: 2,
        label: 'Unmetered',
      },
    ],
  },
  NetworkType: { label: 'Network Type', description: 'Connection type', category: 'device', advanced: true, readonly: true, hidden: true },
  BackupManager_CreateBackup: { label: 'Create Backup', description: 'Backup current settings', category: 'device', advanced: true },
  DeviceBootMode: {
    label: 'Boot Mode',
    description: 'Current device boot mode',
    category: 'device',
    readonly: true,
    hidden: true,
    options: [
      {
        value: 0,
        label: 'Standard',
      },
      {
        value: 1,
        label: 'Always Offroad',
      },
    ],
  },
  UpdaterLastFetchTime: { label: 'Last Update Check', description: 'Time of last update check', category: 'device', readonly: true, hidden: true },
  GitRemote: { label: 'Git Remote', description: 'Git remote origin URL', category: 'device', readonly: true, hidden: true },
  GsmRoaming: { label: 'GSM Roaming', description: 'Allow cellular roaming', category: 'device' },
  IsRhdDetected: { label: 'RHD Detected', description: 'System detected RHD status', category: 'device', readonly: true, hidden: true },
  GitDiff: { label: 'Git Diff', description: 'Local file modifications', category: 'device', readonly: true, hidden: true },
  GitBranch: { label: 'Git Branch', description: 'Current git branch', category: 'device', readonly: true },
  ForcePowerDown: { label: 'Force Power Down', description: 'Force immediate shutdown', category: 'device', advanced: true },
  UptimeOffroad: { label: 'Uptime Offroad', description: 'System idle time', category: 'device', readonly: true },
  GsmApn: { label: 'GSM APN', description: 'Access Point Name', category: 'device', advanced: true },
  RecordFrontLock: { label: 'Lock Front Recording', description: 'Prevent deleting front recordings', category: 'device', advanced: true },
  HasAcceptedTerms: { label: 'Accepted Terms', description: 'User accepted terms', category: 'device', readonly: true, hidden: true },
  HardwareSerial: { label: 'Hardware Serial', description: 'Hardware serial number', category: 'device', readonly: true },
  DoReboot: { label: 'Reboot Device', description: 'Restart the device immediately', category: 'device', advanced: true },
  DoUninstall: { label: 'Uninstall Software', description: 'Uninstall sunnypilot', category: 'device', advanced: true },
  RouteCount: { label: 'Route Count', description: 'Total number of routes', category: 'device', readonly: true },
  GitCommitDate: { label: 'Commit Date', description: 'Date of current commit', category: 'device', readonly: true },
  UptimeOnroad: { label: 'Uptime Onroad', description: 'Session driving time', category: 'device', readonly: true },
  DoShutdown: { label: 'Shutdown Device', description: 'Power off the device immediately', category: 'device', advanced: true },
  OffroadMode: { label: 'Force Offroad Mode', description: 'Forced offroad mode', category: 'device' },
  RecordAudioFeedback: { label: 'Record Audio Feedback', description: 'Audio feedback status', category: 'device', hidden: true },
  BackupManager_RestoreVersion: { label: 'Restore Backup', description: 'Restore settings from backup', category: 'device', advanced: true },
  RecordAudio: { label: 'Record Audio', description: 'Record cabin audio', category: 'device' },

  // Toggles
  DisableLogging: { label: 'Disable Logging', description: 'Stop data logging', category: 'toggles', advanced: true },
  DisableOnroadUploads: { label: 'Disable Onroad Uploads', description: 'No uploads while driving', category: 'toggles' },
  DisablePowerDown: { label: 'Disable Power Down', description: 'Stay on after ignition off', category: 'toggles', advanced: true },
  DisableUpdates: { label: 'Disable Updates', description: 'Skip software updates', category: 'toggles', advanced: true },
  EnableWideCamera: { label: 'Wide Camera', description: 'Use wide-angle camera', category: 'toggles', advanced: true },
  SubaruStopAndGoManualParkingBrake: {
    label: 'Subaru S&G Manual Brake',
    description: 'Subaru Stop&Go manual brake',
    category: 'toggles',
    advanced: true,
  },
  DriverTooDistracted: {
    label: 'Driver is too Distracted',
    description: 'Currently the driver is considered too distracted',
    category: 'toggles',
    readonly: true,
    hidden: true,
  },
  AlwaysOnDM: { label: 'Always On DM', description: 'Always on Driver Monitoring', category: 'toggles' },
  SubaruStopAndGo: { label: 'Subaru Stop & Go', description: 'Enable Subaru Stop & Go', category: 'toggles', advanced: true },
  ExperimentalModeConfirmed: { label: 'Exp Mode Confirmed', description: 'User confirmed exp mode', category: 'toggles', readonly: true, hidden: true },
  DisengageOnAccelerator: { label: 'Disengage on Gas', description: 'Disengage when gas pressed', category: 'toggles' },

  // Steering
  EndToEndLong: { label: 'End-to-End Long', description: 'E2E longitudinal control', category: 'steering' },
  LongitudinalPersonality: {
    label: 'Personality',
    description: 'Driving style preference',
    category: 'steering',
    options: [
      {
        value: 0,
        label: 'Aggressive',
      },
      {
        value: 1,
        label: 'Standard',
      },
      {
        value: 2,
        label: 'Relaxed',
      },
    ],
  },
  LiveTorqueParamsToggle: { label: 'Live Torque Params', description: 'Auto-tune torque parameters', category: 'steering', advanced: true },
  EnforceTorqueControl: { label: 'Enforce Torque Control', description: 'Force torque controller usage', category: 'steering' },
  NeuralNetworkLateralControl: { label: 'NN Lateral Control', description: 'Neural network steering control', category: 'steering' },
  MadsSteeringMode: {
    label: 'MADS Steering Mode',
    description: 'MADS specific steering behavior',
    category: 'steering',
    options: [
      {
        value: 0,
        label: 'Remain Active',
      },
      {
        value: 1,
        label: 'Pause',
      },
      {
        value: 2,
        label: 'Disengage',
      },
    ],
  },
  MadsMainCruiseAllowed: { label: 'MADS Cruise Sync', description: 'Allow MADS with main cruise', category: 'steering' },
  Mads: { label: 'Enable MADS', description: 'Modular Automated Driving System', category: 'steering' },
  MadsUnifiedEngagementMode: { label: 'Unified Engagement', description: 'Engage MADS with Cruise', category: 'steering' },
  HyundaiLongitudinalTuning: {
    label: 'Hyundai Long. Tuning',
    description: 'Longitudinal tuning for Hyundai',
    category: 'steering',
    advanced: true,
    options: [
      {
        value: 0,
        label: 'Off',
      },
      {
        value: 1,
        label: 'Dynamic',
      },
      {
        value: 2,
        label: 'Predictive',
      },
    ],
  },
  HkgTuningOverridingCycles: { label: 'HKG Override Cycles', description: 'Tuning override cycles', category: 'steering', advanced: true },
  HkgTuningAngleActiveTorqueReductionGain: {
    label: 'HKG Active Torque Red.',
    description: 'Active torque reduction gain',
    category: 'steering',
    advanced: true,
  },
  HkgTuningAngleMinTorqueReductionGain: {
    label: 'HKG Min Torque Red.',
    description: 'Minimum torque reduction gain',
    category: 'steering',
    advanced: true,
  },
  EnableHkgTuningAngleSmoothingFactor: { label: 'HKG Angle Smoothing', description: 'Enable angle smoothing', category: 'steering', advanced: true },
  LiveTorqueParamsRelaxedToggle: { label: 'Relaxed Torque Params', description: 'Slower torque learning', category: 'steering', advanced: true },
  LaneTurnValue: { label: 'Lane Turn Value', description: 'Detected lane turn status', category: 'steering', readonly: true, hidden: true },
  TorqueParamsOverrideLatAccelFactor: {
    label: 'Override Lat Accel',
    description: 'Manual lateral accel factor',
    category: 'steering',
    advanced: true,
    hidden: true,
    min: 0.1,
    max: 5.0,
    step: 0.1,
  },
  CustomTorqueParams: { label: 'Custom Torque Params', description: 'Use manual torque values', category: 'steering', advanced: true },
  BlinkerMinLateralControlSpeed: {
    label: 'Blinker Min Lat Speed',
    description: 'Min speed for lat control with blinker',
    category: 'steering',
    advanced: true,
  },
  TorqueParamsOverrideEnabled: { label: 'Override Torque Params', description: 'Enable manual torque override', category: 'steering', advanced: true },
  BlinkerPauseLateralControl: { label: 'Pause Lat on Blinker', description: 'Pause steering when blinking', category: 'steering' },
  TeslaCoopSteering: { label: 'Tesla Coop Steering', description: 'Allow driver steering input', category: 'steering', advanced: true },
  LiveTorqueParameters: { label: 'Live Torque Params', description: 'Current torque parameters', category: 'steering', readonly: true, hidden: true },
  LongitudinalManeuverMode: { label: 'Maneuver Mode', description: 'Specialized maneuver handling', category: 'steering', advanced: true },
  LaneTurnDesire: { label: 'Lane Turn Desire', description: 'Model turn intention', category: 'steering', readonly: true, hidden: true },
  DynamicExperimentalControl: { label: 'Dynamic Experimental', description: 'Auto-toggle experimental mode', category: 'steering', advanced: true },
  HkgTuningAngleMaxTorqueReductionGain: {
    label: 'HKG Max Torque Red.',
    description: 'Maximum torque reduction gain',
    category: 'steering',
    advanced: true,
  },
  TorqueParamsOverrideFriction: {
    label: 'Override Friction',
    description: 'Manual steering friction',
    category: 'steering',
    advanced: true,
    min: 0.0,
    max: 1.0,
    step: 0.01,
  },

  // Cruise
  ExperimentalMode: { label: 'Experimental Mode', description: 'Enable experimental features', category: 'cruise' },
  SmartCruiseControlVision: { label: 'SCC-V', description: 'Vision-based smart cruise', category: 'cruise' },
  SpeedLimitPolicy: {
    label: 'Speed Limit Policy',
    description: 'Policy for speed limit handling',
    category: 'cruise',
    options: [
      {
        value: 0,
        label: 'Car State Only',
      },
      {
        value: 1,
        label: 'Map Data Only',
      },
      {
        value: 2,
        label: 'Car State Priority',
      },
      {
        value: 3,
        label: 'Map Data Priority',
      },
      {
        value: 4,
        label: 'Combined',
      },
    ],
  },
  SpeedLimitOffsetType: {
    label: 'Speed Limit Offset',
    description: 'Offset type (fixed/%)',
    category: 'cruise',
    options: [
      {
        value: 0,
        label: 'Off',
      },
      {
        value: 1,
        label: 'Fixed',
      },
      {
        value: 2,
        label: 'Percentage',
      },
    ],
  },
  SmartCruiseControlMap: { label: 'SCC-M', description: 'Map-based smart cruise', category: 'cruise' },
  MapAdvisorySpeedLimit: { label: 'Map Advisory Speed', description: 'Respect map advisory limits', category: 'cruise' },
  CustomAccLongPressIncrement: {
    label: 'Long Press Increment',
    description: 'Speed change on long press',
    category: 'cruise',
    min: 1,
    max: 10,
    step: 1,
  },
  CustomAccIncrementsEnabled: { label: 'Custom ACC Increments', description: 'Enable custom speed steps', category: 'cruise' },
  AutoLaneChangeBsmDelay: { label: 'BSM Safety Delay', description: 'Blind spot monitoring delay', category: 'cruise', advanced: true },
  IntelligentCruiseButtonManagement: { label: 'Intelligent Cruise Btns', description: 'Enhanced cruise button logic', category: 'cruise' },
  AlphaLongitudinalEnabled: { label: 'Alpha Longitudinal', description: 'Alpha longitudinal control', category: 'cruise', advanced: true },
  SpeedLimitMode: {
    label: 'Speed Limit Mode',
    description: 'How speed limits are handled',
    category: 'cruise',
    options: [
      {
        value: 0,
        label: 'Off',
      },
      {
        value: 1,
        label: 'Information',
      },
      {
        value: 2,
        label: 'Warning',
      },
      {
        value: 3,
        label: 'Assist',
      },
    ],
  },
  CustomAccShortPressIncrement: {
    label: 'Short Press Increment',
    description: 'Speed change on short press',
    category: 'cruise',
    min: 1,
    max: 10,
    step: 1,
  },
  SpeedLimitValueOffset: { label: 'Speed Offset Value', description: 'Value for speed offset', category: 'cruise', min: -30, max: 30, step: 1 },
  AutoLaneChangeTimer: {
    label: 'Auto Lane Change Delay',
    description: 'Wait time before auto change',
    category: 'cruise',
    options: [
      {
        value: -1,
        label: 'Off',
      },
      {
        value: 0,
        label: 'Nudge',
      },
      {
        value: 1,
        label: 'Nudgeless',
      },
      {
        value: 2,
        label: '0.5s',
      },
      {
        value: 3,
        label: '1s',
      },
      {
        value: 4,
        label: '2s',
      },
      {
        value: 5,
        label: '3s',
      },
    ],
  },

  // Visuals
  Brightness: { label: 'Brightness', description: 'Screen brightness level', category: 'visuals' },
  BrightnessOff: { label: 'Brightness (Off)', description: 'Screen brightness when off', category: 'visuals' },
  RoadNameToggle: { label: 'Show Road Name', description: 'Display current road name', category: 'visuals' },
  RoadName: { label: 'Road Name', description: 'Current road name', category: 'visuals', readonly: true, hidden: true },
  BlindSpot: { label: 'Blind Spot', description: 'Blind spot detection enabled', category: 'visuals', readonly: true },
  StandstillTimer: { label: 'Standstill Timer', description: 'Display time spent at standstill', category: 'visuals' },
  RainbowMode: { label: 'Rainbow Mode', description: 'Display rainbow road visualization', category: 'visuals' },
  OnroadScreenOffTimer: { label: 'Screen Off Timer', description: 'Time before screen turns off', category: 'visuals', min: 0, max: 60, step: 1 },
  OnroadScreenOffControl: { label: 'Screen Off Control', description: 'Screen off logic control', category: 'visuals' },
  OnroadScreenOffBrightness: {
    label: 'Screen Off Brightness',
    description: 'Brightness when screen is off',
    category: 'visuals',
    min: 0,
    max: 100,
    step: 5,
  },
  InteractivityTimeout: { label: 'Interactivity Timeout', description: 'Timeout for UI interaction', category: 'visuals', advanced: true },
  GreenLightAlert: { label: 'Green Light Alert', description: 'Alert on green light', category: 'visuals' },
  DevUIInfo: { label: 'Dev UI Info', description: 'Developer UI overlay data', category: 'visuals', readonly: true, hidden: true },
  ChevronInfo: { label: 'Chevron Info', description: 'Lead vehicle distance info', category: 'visuals', readonly: true, hidden: true },
  ShowTurnSignals: { label: 'Show Turn Signals', description: 'Visualize turn signals', category: 'visuals' },
  IsDriverViewEnabled: { label: 'Driver View', description: 'Show driver monitoring camera', category: 'visuals' },
  HideVEgoUI: { label: 'Hide Speed UI', description: 'Hide velocity readout', category: 'visuals' },
  ShowDebugInfo: { label: 'Show Debug Info', description: 'Display developer metrics', category: 'visuals', advanced: true },
  LeadDepartAlert: { label: 'Lead Depart Alert', description: 'Alert when lead car moves', category: 'visuals' },
  TrueVEgoUI: { label: 'True Speed UI', description: 'Show raw vehicle speed', category: 'visuals' },

  // Developer
  ApiCache_DriveStats: {
    label: 'API Cache: Drive Stats',
    description: 'Drive stats cache',
    category: 'developer',
    advanced: true,
    readonly: true,
    hidden: true,
  },
  ApiCache_Device: { label: 'API Cache: Device', description: 'Device info cache', category: 'developer', advanced: true, readonly: true, hidden: true },
  ApiCache_NavDestinations: {
    label: 'API Cache: Nav Destinations',
    description: 'Navigation cache',
    category: 'developer',
    advanced: true,
    readonly: true,
    hidden: true,
  },
  AthenadPid: { label: 'Athena PID', description: 'Athena process ID', category: 'developer', readonly: true, hidden: true },
  BootCount: { label: 'Boot Count', description: 'Number of boots', category: 'developer', advanced: true, readonly: true },
  CalibrationParams: { label: 'Calibration Params', description: 'Camera calibration data', category: 'developer', readonly: true, hidden: true },
  CarBatteryCapacity: { label: 'Car Battery Capacity', description: 'Battery size in kWh', category: 'developer', advanced: true, readonly: true },
  CarParams: { label: 'Car Params', description: 'Vehicle parameters', category: 'developer', readonly: true, hidden: true },
  CarParamsCache: { label: 'Car Params Cache', description: 'Cached vehicle params', category: 'developer', readonly: true, hidden: true },
  CarVin: { label: 'Car VIN', description: 'Vehicle identification', category: 'developer', advanced: true, readonly: true },
  CompletedTrainingVersion: { label: 'Training Version', description: 'Last completed training', category: 'developer', advanced: true, readonly: true },
  ControlsReady: { label: 'Controls Ready', description: 'System ready status', category: 'developer', readonly: true, hidden: true },
  CurrentRoute: { label: 'Current Route', description: 'Active drive route', category: 'developer', readonly: true, hidden: true },
  IMEI: { label: 'IMEI', description: 'Cellular modem ID', category: 'developer', advanced: true, readonly: true },
  InstallDate: { label: 'Install Date', description: 'Installation timestamp', category: 'developer', advanced: true, readonly: true },
  IsEngaged: { label: 'Is Engaged', description: 'Currently engaged', category: 'developer', readonly: true, hidden: true },
  IsFcwEnabled: { label: 'FCW Enabled', description: 'Forward collision warning', category: 'developer', advanced: true, readonly: true },
  IsOffroad: { label: 'Is Offroad', description: 'Not currently driving', category: 'developer', readonly: true, hidden: true },
  IsOnroad: { label: 'Is Onroad', description: 'Currently driving', category: 'developer', readonly: true, hidden: true },
  IsReleaseBranch: { label: 'Is Release Branch', description: 'On release software', category: 'developer', readonly: true, hidden: true },
  IsTestedBranch: { label: 'Is Tested Branch', description: 'On tested software', category: 'developer', readonly: true, hidden: true },
  IsUpdateAvailable: { label: 'Update Available', description: 'Update pending', category: 'developer', readonly: true, hidden: true },
  LastAthenaPingTime: { label: 'Last Athena Ping', description: 'Last server contact', category: 'developer', readonly: true, hidden: true },
  LastGPSPosition: { label: 'Last GPS Position', description: 'GPS coordinates', category: 'developer', readonly: true, hidden: true },
  LastOffroadStatusPacket: { label: 'Last Offroad Packet', description: 'Last status update', category: 'developer', readonly: true, hidden: true },
  LastUpdateException: { label: 'Last Update Exception', description: 'Update error info', category: 'developer', advanced: true, readonly: true },
  LastUpdateTime: { label: 'Last Update Time', description: 'Last update timestamp', category: 'developer', advanced: true, readonly: true },
  LiveParameters: { label: 'Live Parameters', description: 'Runtime parameters', category: 'developer', readonly: true, hidden: true },
  Offroad_BadNvme: { label: 'Offroad: Bad NVMe', description: 'Storage error', category: 'developer', readonly: true, hidden: true },
  Offroad_CarUnrecognized: { label: 'Offroad: Car Unrecognized', description: 'Unknown vehicle', category: 'developer', readonly: true, hidden: true },
  Offroad_ConnectivityNeeded: {
    label: 'Offroad: Connectivity Needed',
    description: 'Internet required',
    category: 'developer',
    readonly: true,
    hidden: true,
  },
  Offroad_InvalidTime: { label: 'Offroad: Invalid Time', description: 'Time sync error', category: 'developer', readonly: true, hidden: true },
  Offroad_IsTakingSnapshot: {
    label: 'Offroad: Taking Snapshot',
    description: 'Snapshot in progress',
    category: 'developer',
    readonly: true,
    hidden: true,
  },
  Offroad_NeosUpdate: { label: 'Offroad: NEOS Update', description: 'OS update required', category: 'developer', readonly: true, hidden: true },
  Offroad_NoFirmware: { label: 'Offroad: No Firmware', description: 'Firmware missing', category: 'developer', readonly: true, hidden: true },
  Offroad_StorageMissing: { label: 'Offroad: Storage Missing', description: 'Storage not found', category: 'developer', readonly: true, hidden: true },
  Offroad_TemperatureTooHigh: { label: 'Offroad: Temperature High', description: 'Overheating', category: 'developer', readonly: true, hidden: true },
  Offroad_UnofficialHardware: {
    label: 'Offroad: Unofficial Hardware',
    description: 'Unsupported device',
    category: 'developer',
    readonly: true,
    hidden: true,
  },
  Offroad_UpdateFailed: { label: 'Offroad: Update Failed', description: 'Update error', category: 'developer', readonly: true, hidden: true },
  Passive: { label: 'Passive', description: 'Passive mode', category: 'developer', readonly: true, hidden: true },
  PrimeRedirected: { label: 'Prime Redirected', description: 'Prime redirect status', category: 'developer', readonly: true, hidden: true },
  PrimeType: { label: 'Prime Type', description: 'Prime subscription type', category: 'developer', readonly: true, hidden: true },
  SnoozeUpdate: { label: 'Snooze Update', description: 'Update snooze timer', category: 'developer', readonly: true, hidden: true },
  SshEnabled: { label: 'SSH Enabled', description: 'SSH access enabled', category: 'developer', advanced: true },
  TermsVersion: { label: 'Terms Version', description: 'Accepted terms version', category: 'developer', readonly: true, hidden: true },
  TrainingVersion: { label: 'Training Version', description: 'Training software version', category: 'developer', readonly: true, hidden: true },
  UpdateAvailable: { label: 'Update Available', description: 'Update ready', category: 'developer', advanced: true, readonly: true },
  UpdateFailedCount: { label: 'Update Failed Count', description: 'Failed update attempts', category: 'developer', advanced: true, readonly: true },
  UpdaterAvailableBranches: { label: 'Available Branches', description: 'Update branches', category: 'developer', advanced: true, readonly: true },
  UpdaterCurrentDescription: { label: 'Current Description', description: 'Current branch info', category: 'developer', readonly: true, hidden: true },
  UpdaterCurrentReleaseNotes: { label: 'Current Release Notes', description: 'Release notes', category: 'developer', readonly: true, hidden: true },
  UpdaterFetchAvailable: { label: 'Updater Fetch Available', description: 'Update check ready', category: 'developer', readonly: true, hidden: true },
  UpdaterNewDescription: { label: 'New Description', description: 'New version info', category: 'developer', readonly: true, hidden: true },
  UpdaterNewReleaseNotes: { label: 'New Release Notes', description: 'New release notes', category: 'developer', readonly: true, hidden: true },
  UpdaterState: { label: 'Updater State', description: 'Update system state', category: 'developer', readonly: true, hidden: true },
  UpdaterTargetBranch: { label: 'Target Branch', description: 'Update target branch', category: 'developer', advanced: true, readonly: true },
  LagdToggleDelay: { label: 'LAQD Toggle Delay', description: 'Delay for LAQD toggle', category: 'developer', advanced: true },
  LagdToggle: { label: 'LAQD Toggle', description: 'Lightweight AQD Toggle', category: 'developer', advanced: true },
  ModelManager_Favs: {
    label: 'Model Favorites',
    description: 'Favorite drive models',
    category: 'developer',
    advanced: true,
    readonly: true,
    hidden: true,
  },
  ModelManager_ActiveBundle: {
    label: 'Active Model Bundle',
    description: 'Currently active model',
    category: 'developer',
    advanced: true,
    readonly: true,
  },
  ShowAdvancedControls: { label: 'Show Advanced Controls', description: 'Unlock advanced settings', category: 'developer', advanced: true },
  QuickBootToggle: { label: 'Quick Boot', description: 'Enable quick boot', category: 'developer', advanced: true },
  ModelManager_ModelsCache: { label: 'Model Cache', description: 'Cached model list', category: 'developer', readonly: true, hidden: true },
  Offroad_TiciSupport: { label: 'TiCi Support', description: 'TiCi hardware support status', category: 'developer', readonly: true, hidden: true },
  IsReleaseSpBranch: { label: 'SP Release Branch', description: 'On Sunnypilot release branch', category: 'developer', readonly: true, hidden: true },
  SunnylinkEnabled: { label: 'sunnylink Enabled', description: 'Enable sunnylink services', category: 'developer', hidden: true },
  EnableCopyparty: { label: 'Enable File Server', description: 'Start Copyparty file server', category: 'developer', advanced: true },
  CarParamsSPCache: { label: 'SP Car Params Cache', description: 'Cached Sunnypilot car params', category: 'developer', readonly: true, hidden: true },
  CarParamsSP: { label: 'SP Car Params', description: 'Sunnypilot vehicle parameters', category: 'developer', readonly: true, hidden: true },
  ModelRunnerTypeCache: { label: 'Model Runner Type', description: 'Inference engine type', category: 'developer', readonly: true, hidden: true },
  OnroadCycleRequested: { label: 'Onroad Cycle', description: 'Cycle start requested', category: 'developer', readonly: true, hidden: true },
  GithubRunnerSufficientVoltage: { label: 'Runner Voltage Check', description: 'Check voltage for GitHub runner', category: 'developer', advanced: true },
  CameraDebugExpGain: { label: 'Cam Debug Gain', description: 'Camera exposure gain', category: 'developer', readonly: true, hidden: true },
  ApiCache_FirehoseStats: { label: 'Firehose Stats', description: 'Cached streaming stats', category: 'developer', readonly: true, hidden: true },
  JoystickDebugMode: { label: 'Joystick Debug', description: 'Enable joystick debugging', category: 'developer', advanced: true },
  EnableWebRTC: { label: 'Enable WebRTC', description: 'Allow remote live streaming', category: 'developer', advanced: true },
  EnableRemoteParams: { label: 'Enable Remote Params', description: 'Allow remote parameter editing', category: 'developer', advanced: true },
  ModelManager_LastSyncTime: { label: 'Model Sync Time', description: 'Last model list sync', category: 'developer', readonly: true, hidden: true },
  IsDevelopmentBranch: { label: 'Dev Branch', description: 'On development channel', category: 'developer', readonly: true, hidden: true },
  AthenadUploadQueue: { label: 'Upload Queue', description: 'Files queued for upload', category: 'developer', readonly: true, hidden: true },
  AssistNowToken: { label: 'AssistNow Token', description: 'GPS assist token', category: 'developer', readonly: true, hidden: true },
  CarParamsPrevRoute: { label: 'Previous Route Params', description: 'Params from previous route', category: 'developer', readonly: true, hidden: true },
  CarPlatformBundle: { label: 'Car Platform Bundle', description: 'Platform specific code', category: 'developer', readonly: true, hidden: true },
  AdbEnabled: { label: 'ADB Enabled', description: 'Android Debug Bridge', category: 'developer', advanced: true },
  ObdMultiplexingChanged: { label: 'OBD Multiplex Changed', description: 'Multiplexing setting changed', category: 'developer', readonly: true, hidden: true },
  EnableSunnylinkUploader: { label: 'sunnylink Uploader', description: 'Upload drives to sunnylink', category: 'developer' },
  CameraDebugExpTime: { label: 'Cam Debug Time', description: 'Camera exposure time', category: 'developer', readonly: true, hidden: true },
  FirmwareQueryDone: { label: 'Firmware Query Done', description: 'Firmware check complete', category: 'developer', readonly: true, hidden: true },
  ModelManager_DownloadIndex: { label: 'Model Download Index', description: 'Download queue index', category: 'developer', readonly: true, hidden: true },
  ModelManager_ClearCache: { label: 'Clear Model Cache', description: 'Delete downloaded models', category: 'developer', advanced: true },
  CurrentBootlog: { label: 'Current Bootlog', description: 'Log of current boot', category: 'developer', readonly: true, hidden: true },
  Offroad_ExcessiveActuation: {
    label: 'Excessive Actuation',
    description: 'Controls saturation detected',
    category: 'developer',
    readonly: true,
    hidden: true,
  },
  LastManagerExitReason: { label: 'Exit Reason', description: 'Reason for last process exit', category: 'developer', readonly: true, hidden: true },
  CarParamsSPPersistent: { label: 'Car Params SP Persist', description: 'Persistent SP params', category: 'developer', readonly: true, hidden: true },
  SecOCKey: { label: 'SecOC Key', description: 'Security key', category: 'developer', readonly: true, hidden: true },
  LastPowerDropDetected: { label: 'Power Drop', description: 'Last power drop event', category: 'developer', readonly: true, hidden: true },
  OnroadUploads: { label: 'Onroad Uploads', description: 'Upload status', category: 'developer', readonly: true, hidden: true },
  LiveParametersV2: { label: 'Live Parameters V2', description: 'Runtime vehicle params V2', category: 'developer', readonly: true, hidden: true },
  LastUpdateRouteCount: { label: 'Last Update Route Count', description: 'Routes since last update', category: 'developer', readonly: true, hidden: true },
  LastUpdateUptimeOnroad: { label: 'Last Update Uptime', description: 'Driving time since update', category: 'developer', readonly: true, hidden: true },
  LagdValueCache: { label: 'LAQD Value Cache', description: 'Cached LAQD values', category: 'developer', readonly: true, hidden: true },
  EnableGithubRunner: { label: 'GitHub Runner', description: 'Enable CI/CD runner', category: 'developer', advanced: true },
  LiveDelay: { label: 'Live Delay', description: 'Communication delay', category: 'developer', readonly: true, hidden: true },
  LocationFilterInitialState: { label: 'Loc Filter Init', description: 'Location filter state', category: 'developer', readonly: true, hidden: true },
  PandaHeartbeatLost: { label: 'Panda Heartbeat Lost', description: 'Comms loss status', category: 'developer', readonly: true, hidden: true },
  Offroad_ConnectivityNeededPrompt: {
    label: 'Conn Needed Prompt',
    description: 'Prompt for internet',
    category: 'developer',
    readonly: true,
    hidden: true,
  },
  Offroad_Recalibration: { label: 'Recalibration', description: 'Recalibration required', category: 'developer', readonly: true, hidden: true },
  Offroad_UnregisteredHardware: { label: 'Unregistered', description: 'Device not registered', category: 'developer', readonly: true, hidden: true },
  LastGPSPositionLLK: { label: 'Last GPS LLK', description: 'Last precise GPS loc', category: 'developer', readonly: true, hidden: true },
  ObdMultiplexingEnabled: { label: 'OBD Multiplexing', description: 'Enable OBD multiplexing', category: 'developer', advanced: true },
  Offroad_DriverMonitoringUncertain: {
    label: 'DM Uncertain',
    description: 'Driver monitoring checking',
    category: 'developer',
    readonly: true,
    hidden: true,
  },
  PandaSomResetTriggered: { label: 'Panda Reset Triggered', description: 'Reset trigger status', category: 'developer', readonly: true, hidden: true },
  PandaSignatures: { label: 'Panda Signatures', description: 'Firmware signatures', category: 'developer', readonly: true, hidden: true },
  UbloxAvailable: { label: 'Ublox GPS Available', description: 'GPS hardware status', category: 'developer', readonly: true, hidden: true },
  CarParamsPersistent: { label: 'Car Params Persistent', description: 'Persistent vehicle params', category: 'developer', readonly: true, hidden: true },
  IsTakingSnapshot: { label: 'Snapshotting', description: 'Camera capturing', category: 'developer', readonly: true, hidden: true },

  // Other
  NavDestination: { label: 'Nav Destination', description: 'Navigation target', category: 'other', readonly: true, hidden: true },
  NavSettingLeftSide: { label: 'Nav Left Side', description: 'Left-side navigation', category: 'other', advanced: true, hidden: true },
  NavSettingTime24h: { label: 'Nav 24h Time', description: '24-hour time format', category: 'other', advanced: true, hidden: true },
  NavdRender: { label: 'Nav Render', description: 'Navigation rendering', category: 'other', advanced: true, hidden: true },
  OsmStateName: { label: 'State Code', description: 'Current OSM state code', category: 'other', readonly: true, hidden: true },
  OsmLocationTitle: { label: 'Location Title', description: 'Current location title', category: 'other', readonly: true, hidden: true },
  OsmLocationName: { label: 'Location Name', description: 'Current location details', category: 'other', readonly: true, hidden: true },
  OSMDownloadProgress: { label: 'Map Download Progress', description: 'Map download status', category: 'other', readonly: true, hidden: true },
  OSMDownloadLocations: { label: 'Map Download Locations', description: 'Queued map downloads', category: 'other', readonly: true, hidden: true },
  OsmDownloadedDate: { label: 'Map Data Date', description: 'Date of downloaded maps', category: 'other', readonly: true, hidden: true },
  Offroad_OSMUpdateRequired: { label: 'Map Update Required', description: 'OSM maps need update', category: 'other', readonly: true, hidden: true },
  MapdVersion: { label: 'Mapd Version', description: 'Map daemon version', category: 'other', readonly: true, hidden: true },
  SunnylinkTempFault: { label: 'sunnylink Fault', description: 'Temporary connection fault', category: 'other', readonly: true, hidden: true },
  SunnylinkCache_Users: { label: 'sunnylink User Cache', description: 'Cached user data', category: 'other', readonly: true, hidden: true },
  SunnylinkCache_Roles: { label: 'sunnylink Role Cache', description: 'Cached role data', category: 'other', readonly: true, hidden: true },
  SunnylinkDongleId: { label: 'sunnylink ID', description: 'sunnylink device identifier', category: 'other', readonly: true },
  MapSpeedLimit: { label: 'Map Speed Limit', description: 'Current speed limit from map', category: 'other', readonly: true, hidden: true },
  OSMDownloadBounds: { label: 'Map Download Bounds', description: 'Map area boundaries', category: 'other', readonly: true, hidden: true },
  OsmDbUpdatesCheck: { label: 'Map Updates Check', description: 'Last map update check', category: 'other', readonly: true, hidden: true },
  AthenadRecentlyViewedRoutes: { label: 'Recent Routes', description: 'Recently viewed routes cache', category: 'other', readonly: true, hidden: true },
  OsmLocationUrl: { label: 'Location URL', description: 'OSM Location Link', category: 'other', readonly: true, hidden: true },
  AccessToken: { label: 'Access Token', description: 'API Access Token', category: 'other', readonly: true, hidden: true },
  SunnylinkdPid: { label: 'sunnylink PID', description: 'sunnylink process ID', category: 'other', readonly: true, hidden: true },
  OsmLocal: { label: 'Local OSM', description: 'Use local OSM server', category: 'other', advanced: true, hidden: true },
  MapTargetVelocities: { label: 'Map Target Velocities', description: 'Map-based velocity targets', category: 'other', readonly: true, hidden: true },
  OsmWayTest: { label: 'OSM Way Test', description: 'Debug OSM way query', category: 'other', advanced: true, hidden: true },
  NextMapSpeedLimit: { label: 'Next Map Speed', description: 'Upcoming speed limit', category: 'other', readonly: true, hidden: true },
  OsmStateTitle: { label: 'State Region', description: 'Current OSM region', category: 'other', readonly: true, hidden: true },
  LastSunnylinkPingTime: { label: 'LastSunnylinkPingTime', description: 'Unknown setting from device', category: 'other', hidden: true },
  WebRTCOnline: { label: '', description: '', category: 'other', hidden: true },
  LastAgnosPowerMonitorShutdown: { label: '', description: '', category: 'other', hidden: true },
  CarList: { label: '', description: '', category: 'other', hidden: true },
}
export type DeviceParamKey = keyof typeof DEVICE_PARAMS
