import { z } from 'zod'

export const SettingCategory = z.enum(['models', 'device', 'toggles', 'steering', 'cruise', 'visuals', 'developer', 'other'])
export type SettingCategory = z.infer<typeof SettingCategory>

export type DeviceParam = {
  label: string
  description: string
  category: SettingCategory
  icon: string
  advanced?: boolean
  readonly?: boolean
  hidden?: boolean
  options?: { value: number; label: string }[]
  min?: number
  max?: number
  step?: number
  type: ParamType
}

export enum ParamType {
  STRING = 0,
  BOOL = 1,
  INT = 2,
  FLOAT = 3,
  TIME = 4,
  JSON = 5,
  BYTES = 6,
}
export const getParamType = (value: any): ParamType => {
  if (typeof value === 'boolean') return ParamType.BOOL
  if (typeof value === 'number') return ParamType.FLOAT
  if (typeof value === 'string') return ParamType.STRING
  if (typeof value === 'object') return ParamType.JSON
  throw new Error(`Invalid param ${value}`)
}
export type DeviceParamKey = keyof typeof DEVICE_PARAMS

export const DEVICE_PARAMS = {
  DongleId: { label: 'Dongle ID', description: 'Unique device identifier', category: 'device', icon: 'fingerprint', readonly: true, type: ParamType.STRING },
  GitCommit: { label: 'Git Commit', description: 'Current software version', category: 'device', icon: 'commit', readonly: true, type: ParamType.STRING },
  GithubSshKeys: {
    label: 'GitHub SSH Keys',
    description: 'SSH keys for GitHub access',
    category: 'device',
    icon: 'vpn_key',
    readonly: true,
    type: ParamType.STRING,
  },
  GithubUsername: {
    label: 'GitHub Username',
    description: 'Connected GitHub account',
    category: 'device',
    icon: 'person',
    readonly: true,
    type: ParamType.STRING,
  },
  GsmMetered: { label: 'GSM Metered', description: 'Cellular data metering', category: 'device', icon: 'data_usage', type: ParamType.BOOL },
  IsLdwEnabled: { label: 'LDW Enabled', description: 'Lane departure warnings', category: 'device', icon: 'warning', type: ParamType.BOOL },
  IsMetric: { label: 'Metric Units', description: 'Display metric measurements', category: 'device', icon: 'straighten', type: ParamType.BOOL },
  LanguageSetting: { label: 'Language', description: 'UI language', category: 'device', icon: 'language', type: ParamType.STRING },
  OpenpilotEnabledToggle: {
    label: 'sunnypilot Enabled',
    description: 'Master sunnypilot toggle',
    category: 'device',
    icon: 'toggle_on',
    type: ParamType.BOOL,
  },
  RecordFront: { label: 'Record Front', description: 'Front camera recording', category: 'device', icon: 'videocam', type: ParamType.BOOL },
  IsRHD: { label: 'Right-Hand Drive', description: 'RHD vehicle configuration', category: 'device', icon: 'directions_car', type: ParamType.BOOL },
  Version: { label: 'Version', description: 'Software version number', category: 'device', icon: 'info', readonly: true, type: ParamType.STRING },
  QuietMode: { label: 'Quiet Mode', description: 'Minimize sound notifications', category: 'device', icon: 'volume_off', type: ParamType.BOOL },
  MaxTimeOffroad: {
    label: 'Max Time Offroad',
    description: 'Max idle time before shutdown',
    category: 'device',
    icon: 'timer',
    advanced: true,
    type: ParamType.INT,
  },
  NetworkMetered: {
    label: 'Network Metered',
    description: 'Metered connection',
    category: 'device',
    icon: 'network_cell',
    advanced: true,
    hidden: true,
    options: [
      { value: 0, label: 'Default' },
      { value: 1, label: 'Metered' },
      { value: 2, label: 'Unmetered' },
    ],
    type: ParamType.BOOL,
  },
  NetworkType: {
    label: 'Network Type',
    description: 'Connection type',
    category: 'device',
    icon: 'wifi',
    advanced: true,
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  BackupManager_CreateBackup: {
    label: 'Create Backup',
    description: 'Backup current settings',
    category: 'device',
    icon: 'backup',
    advanced: true,
    type: ParamType.BOOL,
  },
  DeviceBootMode: {
    label: 'Boot Mode',
    description: 'Current device boot mode',
    category: 'device',
    icon: 'developer_mode',
    readonly: true,
    hidden: true,
    options: [
      { value: 0, label: 'Standard' },
      { value: 1, label: 'Always Offroad' },
    ],
    type: ParamType.INT,
  },
  UpdaterLastFetchTime: {
    label: 'Last Update Check',
    description: 'Time of last update check',
    category: 'device',
    icon: 'schedule',
    readonly: true,
    hidden: true,
    type: ParamType.TIME,
  },
  GitRemote: {
    label: 'Git Remote',
    description: 'Git remote origin URL',
    category: 'device',
    icon: 'link',
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  GsmRoaming: { label: 'GSM Roaming', description: 'Allow cellular roaming', category: 'device', icon: 'cell_tower', type: ParamType.BOOL },
  IsRhdDetected: {
    label: 'RHD Detected',
    description: 'System detected RHD status',
    category: 'device',
    icon: 'directions_car',
    readonly: true,
    hidden: true,
    type: ParamType.BOOL,
  },
  GitDiff: {
    label: 'Git Diff',
    description: 'Local file modifications',
    category: 'device',
    icon: 'description',
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  GitBranch: { label: 'Git Branch', description: 'Current git branch', category: 'device', icon: 'commit', readonly: true, type: ParamType.STRING },
  ForcePowerDown: {
    label: 'Force Power Down',
    description: 'Force immediate shutdown',
    category: 'device',
    icon: 'power_settings_new',
    advanced: true,
    type: ParamType.BOOL,
  },
  UptimeOffroad: { label: 'Uptime Offroad', description: 'System idle time', category: 'device', icon: 'timer', readonly: true, type: ParamType.FLOAT },
  GsmApn: { label: 'GSM APN', description: 'Access Point Name', category: 'device', icon: 'sim_card', advanced: true, type: ParamType.STRING },
  RecordFrontLock: {
    label: 'Lock Front Recording',
    description: 'Prevent deleting front recordings',
    category: 'device',
    icon: 'lock',
    advanced: true,
    type: ParamType.BOOL,
  },
  HasAcceptedTerms: {
    label: 'Accepted Terms',
    description: 'User accepted terms',
    category: 'device',
    icon: 'verified_user',
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  HardwareSerial: {
    label: 'Hardware Serial',
    description: 'Hardware serial number',
    category: 'device',
    icon: 'memory',
    readonly: true,
    type: ParamType.STRING,
  },
  DoReboot: {
    label: 'Reboot Device',
    description: 'Restart the device immediately',
    category: 'device',
    icon: 'restart_alt',
    advanced: true,
    type: ParamType.BOOL,
  },
  DoUninstall: {
    label: 'Uninstall Software',
    description: 'Uninstall sunnypilot',
    category: 'device',
    icon: 'delete_forever',
    advanced: true,
    type: ParamType.BOOL,
  },
  RouteCount: {
    label: 'Route Count',
    description: 'Total number of routes',
    category: 'device',
    icon: 'counter_1',
    readonly: true,
    type: ParamType.INT,
  },
  GitCommitDate: { label: 'Commit Date', description: 'Date of current commit', category: 'device', icon: 'schedule', readonly: true, type: ParamType.STRING },
  UptimeOnroad: { label: 'Uptime Onroad', description: 'Session driving time', category: 'device', icon: 'timer', readonly: true, type: ParamType.FLOAT },
  DoShutdown: {
    label: 'Shutdown Device',
    description: 'Power off the device immediately',
    category: 'device',
    icon: 'power_settings_new',
    advanced: true,
    type: ParamType.BOOL,
  },
  OffroadMode: { label: 'Force Offroad Mode', description: 'Forced offroad mode', category: 'device', icon: 'directions_car', type: ParamType.BOOL },
  RecordAudioFeedback: {
    label: 'Record Audio Feedback',
    description: 'Audio feedback status',
    category: 'device',
    icon: 'mic',
    hidden: true,
    type: ParamType.BOOL,
  },
  BackupManager_RestoreVersion: {
    label: 'Restore Backup',
    description: 'Restore settings from backup',
    category: 'device',
    icon: 'backup',
    advanced: true,
    type: ParamType.STRING,
  },
  RecordAudio: { label: 'Record Audio', description: 'Record cabin audio', category: 'device', icon: 'mic', type: ParamType.BOOL },
  DisableLogging: { label: 'Disable Logging', description: 'Stop data logging', category: 'toggles', icon: 'block', advanced: true, type: ParamType.BOOL },
  DisableOnroadUploads: {
    label: 'Disable Onroad Uploads',
    description: 'No uploads while driving',
    category: 'toggles',
    icon: 'cloud_off',
    type: ParamType.BOOL,
  },
  DisablePowerDown: {
    label: 'Disable Power Down',
    description: 'Stay on after ignition off',
    category: 'toggles',
    icon: 'power_settings_new',
    advanced: true,
    type: ParamType.BOOL,
  },
  DisableUpdates: {
    label: 'Disable Updates',
    description: 'Skip software updates',
    category: 'toggles',
    icon: 'update',
    advanced: true,
    type: ParamType.BOOL,
  },
  EnableWideCamera: {
    label: 'Wide Camera',
    description: 'Use wide-angle camera',
    category: 'toggles',
    icon: 'wide_angle_camera',
    advanced: true,
    type: ParamType.BOOL,
  },
  SubaruStopAndGoManualParkingBrake: {
    label: 'Subaru S&G Manual Brake',
    description: 'Subaru Stop&Go manual brake',
    category: 'toggles',
    icon: 'pan_tool',
    advanced: true,
    type: ParamType.BOOL,
  },
  DriverTooDistracted: {
    label: 'Driver is too Distracted',
    description: 'Currently the driver is considered too distracted',
    category: 'toggles',
    icon: 'remove_red_eye',
    readonly: true,
    hidden: true,
    type: ParamType.BOOL,
  },
  AlwaysOnDM: { label: 'Always On DM', description: 'Always on Driver Monitoring', category: 'toggles', icon: 'visibility', type: ParamType.BOOL },
  SubaruStopAndGo: {
    label: 'Subaru Stop & Go',
    description: 'Enable Subaru Stop & Go',
    category: 'toggles',
    icon: 'directions_car',
    advanced: true,
    type: ParamType.BOOL,
  },
  ExperimentalModeConfirmed: {
    label: 'Exp Mode Confirmed',
    description: 'User confirmed exp mode',
    category: 'toggles',
    icon: 'check',
    readonly: true,
    hidden: true,
    type: ParamType.BOOL,
  },
  DisengageOnAccelerator: {
    label: 'Disengage on Gas',
    description: 'Disengage when gas pressed',
    category: 'toggles',
    icon: 'speed',
    type: ParamType.BOOL,
  },
  EndToEndLong: { label: 'End-to-End Long', description: 'E2E longitudinal control', category: 'steering', icon: 'trending_up', type: ParamType.BOOL },
  LongitudinalPersonality: {
    label: 'Personality',
    description: 'Driving style preference',
    category: 'steering',
    icon: 'psychology',
    options: [
      { value: 0, label: 'Aggressive' },
      { value: 1, label: 'Standard' },
      { value: 2, label: 'Relaxed' },
    ],
    type: ParamType.INT,
  },
  LiveTorqueParamsToggle: {
    label: 'Live Torque Params',
    description: 'Auto-tune torque parameters',
    category: 'steering',
    icon: 'sync',
    advanced: true,
    type: ParamType.BOOL,
  },
  EnforceTorqueControl: {
    label: 'Enforce Torque Control',
    description: 'Force torque controller usage',
    category: 'steering',
    icon: 'auto_fix_high',
    type: ParamType.BOOL,
  },
  NeuralNetworkLateralControl: {
    label: 'NN Lateral Control',
    description: 'Neural network steering control',
    category: 'steering',
    icon: 'model_training',
    type: ParamType.BOOL,
  },
  MadsSteeringMode: {
    label: 'MADS Steering Mode',
    description: 'MADS specific steering behavior',
    category: 'steering',
    icon: 'steering',
    options: [
      { value: 0, label: 'Remain Active' },
      { value: 1, label: 'Pause' },
      { value: 2, label: 'Disengage' },
    ],
    type: ParamType.INT,
  },
  MadsMainCruiseAllowed: {
    label: 'MADS Cruise Sync',
    description: 'Allow MADS with main cruise',
    category: 'steering',
    icon: 'swap_horiz',
    type: ParamType.BOOL,
  },
  Mads: { label: 'Enable MADS', description: 'Modular Automated Driving System', category: 'steering', icon: 'steering', type: ParamType.BOOL },
  MadsUnifiedEngagementMode: {
    label: 'Unified Engagement',
    description: 'Engage MADS with Cruise',
    category: 'steering',
    icon: 'sync',
    type: ParamType.BOOL,
  },
  HyundaiLongitudinalTuning: {
    label: 'Hyundai Long. Tuning',
    description: 'Longitudinal tuning for Hyundai',
    category: 'steering',
    icon: 'tune',
    advanced: true,
    options: [
      { value: 0, label: 'Off' },
      { value: 1, label: 'Dynamic' },
      { value: 2, label: 'Predictive' },
    ],
    type: ParamType.INT,
  },
  HkgTuningOverridingCycles: {
    label: 'HKG Override Cycles',
    description: 'Tuning override cycles',
    category: 'steering',
    icon: 'timeline',
    advanced: true,
    type: ParamType.INT,
  },
  HkgTuningAngleActiveTorqueReductionGain: {
    label: 'HKG Active Torque Red.',
    description: 'Active torque reduction gain',
    category: 'steering',
    icon: 'slow_motion_video',
    advanced: true,
    type: ParamType.FLOAT,
  },
  HkgTuningAngleMinTorqueReductionGain: {
    label: 'HKG Min Torque Red.',
    description: 'Minimum torque reduction gain',
    category: 'steering',
    icon: 'slow_motion_video',
    advanced: true,
    type: ParamType.FLOAT,
  },
  EnableHkgTuningAngleSmoothingFactor: {
    label: 'HKG Angle Smoothing',
    description: 'Enable angle smoothing',
    category: 'steering',
    icon: 'tune',
    advanced: true,
    type: ParamType.BOOL,
  },
  LiveTorqueParamsRelaxedToggle: {
    label: 'Relaxed Torque Params',
    description: 'Slower torque learning',
    category: 'steering',
    icon: 'sync',
    advanced: true,
    type: ParamType.BOOL,
  },
  LaneTurnValue: {
    label: 'Lane Turn Value',
    description: 'Detected lane turn status',
    category: 'steering',
    icon: 'turn_slight_right',
    readonly: true,
    hidden: true,
    type: ParamType.FLOAT,
  },
  TorqueParamsOverrideLatAccelFactor: {
    label: 'Override Lat Accel',
    description: 'Manual lateral accel factor',
    category: 'steering',
    icon: 'edit',
    advanced: true,
    hidden: true,
    min: 0.1,
    max: 5,
    step: 0.1,
    type: ParamType.FLOAT,
  },
  CustomTorqueParams: {
    label: 'Custom Torque Params',
    description: 'Use manual torque values',
    category: 'steering',
    icon: 'tune',
    advanced: true,
    type: ParamType.BOOL,
  },
  BlinkerMinLateralControlSpeed: {
    label: 'Blinker Min Lat Speed',
    description: 'Min speed for lat control with blinker',
    category: 'steering',
    icon: 'flash_on',
    advanced: true,
    type: ParamType.INT,
  },
  TorqueParamsOverrideEnabled: {
    label: 'Override Torque Params',
    description: 'Enable manual torque override',
    category: 'steering',
    icon: 'edit',
    advanced: true,
    type: ParamType.BOOL,
  },
  BlinkerPauseLateralControl: {
    label: 'Pause Lat on Blinker',
    description: 'Pause steering when blinking',
    category: 'steering',
    icon: 'flash_on',
    type: ParamType.INT,
  },
  LiveTorqueParameters: {
    label: 'Live Torque Params',
    description: 'Current torque parameters',
    category: 'steering',
    icon: 'tune',
    readonly: true,
    hidden: true,
    type: ParamType.BYTES,
  },
  LongitudinalManeuverMode: {
    label: 'Maneuver Mode',
    description: 'Specialized maneuver handling',
    category: 'steering',
    icon: 'directions_car',
    advanced: true,
    type: ParamType.BOOL,
  },
  LaneTurnDesire: {
    label: 'Lane Turn Desire',
    description: 'Model turn intention',
    category: 'steering',
    icon: 'turn_slight_right',
    readonly: true,
    hidden: true,
    type: ParamType.BOOL,
  },
  DynamicExperimentalControl: {
    label: 'Dynamic Experimental',
    description: 'Auto-toggle experimental mode',
    category: 'steering',
    icon: 'science',
    advanced: true,
    type: ParamType.BOOL,
  },
  HkgTuningAngleMaxTorqueReductionGain: {
    label: 'HKG Max Torque Red.',
    description: 'Maximum torque reduction gain',
    category: 'steering',
    icon: 'slow_motion_video',
    advanced: true,
    type: ParamType.FLOAT,
  },
  TorqueParamsOverrideFriction: {
    label: 'Override Friction',
    description: 'Manual steering friction',
    category: 'steering',
    icon: 'edit',
    advanced: true,
    min: 0,
    max: 1,
    step: 0.01,
    type: ParamType.FLOAT,
  },
  ExperimentalMode: { label: 'Experimental Mode', description: 'Enable experimental features', category: 'cruise', icon: 'science', type: ParamType.BOOL },
  SmartCruiseControlVision: { label: 'SCC-V', description: 'Vision-based smart cruise', category: 'cruise', icon: 'visibility', type: ParamType.BOOL },
  SpeedLimitPolicy: {
    label: 'Speed Limit Policy',
    description: 'Policy for speed limit handling',
    category: 'cruise',
    icon: 'speed',
    options: [
      { value: 0, label: 'Car State Only' },
      { value: 1, label: 'Map Data Only' },
      { value: 2, label: 'Car State Priority' },
      { value: 3, label: 'Map Data Priority' },
      { value: 4, label: 'Combined' },
    ],
    type: ParamType.INT,
  },
  SpeedLimitOffsetType: {
    label: 'Speed Limit Offset',
    description: 'Offset type (fixed/%)',
    category: 'cruise',
    icon: 'speed',
    options: [
      { value: 0, label: 'Off' },
      { value: 1, label: 'Fixed' },
      { value: 2, label: 'Percentage' },
    ],
    type: ParamType.INT,
  },
  SmartCruiseControlMap: { label: 'SCC-M', description: 'Map-based smart cruise', category: 'cruise', icon: 'map', type: ParamType.BOOL },
  MapAdvisorySpeedLimit: {
    label: 'Map Advisory Speed',
    description: 'Respect map advisory limits',
    category: 'cruise',
    icon: 'signpost',
    type: ParamType.FLOAT,
  },
  CustomAccLongPressIncrement: {
    label: 'Long Press Increment',
    description: 'Speed change on long press',
    category: 'cruise',
    icon: 'add',
    min: 1,
    max: 10,
    step: 1,
    type: ParamType.INT,
  },
  CustomAccIncrementsEnabled: {
    label: 'Custom ACC Increments',
    description: 'Enable custom speed steps',
    category: 'cruise',
    icon: 'tune',
    type: ParamType.BOOL,
  },
  AutoLaneChangeBsmDelay: {
    label: 'BSM Safety Delay',
    description: 'Blind spot monitoring delay',
    category: 'cruise',
    icon: 'timer',
    advanced: true,
    type: ParamType.BOOL,
  },
  IntelligentCruiseButtonManagement: {
    label: 'Intelligent Cruise Btns',
    description: 'Enhanced cruise button logic',
    category: 'cruise',
    icon: 'gamepad',
    type: ParamType.BOOL,
  },
  AlphaLongitudinalEnabled: {
    label: 'Alpha Longitudinal',
    description: 'Alpha longitudinal control',
    category: 'cruise',
    icon: 'science',
    advanced: true,
    type: ParamType.BOOL,
  },
  SpeedLimitMode: {
    label: 'Speed Limit Mode',
    description: 'How speed limits are handled',
    category: 'cruise',
    icon: 'speed_limit',
    options: [
      { value: 0, label: 'Off' },
      { value: 1, label: 'Information' },
      { value: 2, label: 'Warning' },
      { value: 3, label: 'Assist' },
    ],
    type: ParamType.INT,
  },
  CustomAccShortPressIncrement: {
    label: 'Short Press Increment',
    description: 'Speed change on short press',
    category: 'cruise',
    icon: 'add',
    min: 1,
    max: 10,
    step: 1,
    type: ParamType.INT,
  },
  SpeedLimitValueOffset: {
    label: 'Speed Offset Value',
    description: 'Value for speed offset',
    category: 'cruise',
    icon: 'speed',
    min: -30,
    max: 30,
    step: 1,
    type: ParamType.INT,
  },
  AutoLaneChangeTimer: {
    label: 'Auto Lane Change Delay',
    description: 'Wait time before auto change',
    category: 'cruise',
    icon: 'swap_horiz',
    options: [
      { value: -1, label: 'Off' },
      { value: 0, label: 'Nudge' },
      { value: 1, label: 'Nudgeless' },
      { value: 2, label: '0.5s' },
      { value: 3, label: '1s' },
      { value: 4, label: '2s' },
      { value: 5, label: '3s' },
    ],
    type: ParamType.INT,
  },
  Brightness: { label: 'Brightness', description: 'Screen brightness level', category: 'visuals', icon: 'brightness_6', type: ParamType.INT },
  BrightnessOff: {
    label: 'Brightness (Off)',
    description: 'Screen brightness when off',
    category: 'visuals',
    icon: 'brightness_low',
    type: ParamType.INT,
  },
  RoadNameToggle: { label: 'Show Road Name', description: 'Display current road name', category: 'visuals', icon: 'signpost', type: ParamType.STRING },
  RoadName: {
    label: 'Road Name',
    description: 'Current road name',
    category: 'visuals',
    icon: 'signpost',
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  BlindSpot: {
    label: 'Blind Spot',
    description: 'Blind spot detection enabled',
    category: 'visuals',
    icon: 'visibility',
    readonly: true,
    type: ParamType.BOOL,
  },
  StandstillTimer: { label: 'Standstill Timer', description: 'Display time spent at standstill', category: 'visuals', icon: 'timer', type: ParamType.BOOL },
  RainbowMode: { label: 'Rainbow Mode', description: 'Display rainbow road visualization', category: 'visuals', icon: 'star', type: ParamType.BOOL },
  OnroadScreenOffTimer: {
    label: 'Screen Off Timer',
    description: 'Time before screen turns off',
    category: 'visuals',
    icon: 'timer_off',
    min: 0,
    max: 60,
    step: 1,
    type: ParamType.INT,
  },
  OnroadScreenOffControl: {
    label: 'Screen Off Control',
    description: 'Screen off logic control',
    category: 'visuals',
    icon: 'nightlight',
    type: ParamType.BOOL,
  },
  OnroadScreenOffBrightness: {
    label: 'Screen Off Brightness',
    description: 'Brightness when screen is off',
    category: 'visuals',
    icon: 'brightness_low',
    min: 0,
    max: 100,
    step: 5,
    type: ParamType.INT,
  },
  InteractivityTimeout: {
    label: 'Interactivity Timeout',
    description: 'Timeout for UI interaction',
    category: 'visuals',
    icon: 'timer',
    advanced: true,
    type: ParamType.INT,
  },
  GreenLightAlert: { label: 'Green Light Alert', description: 'Alert on green light', category: 'visuals', icon: 'traffic', type: ParamType.BOOL },
  DevUIInfo: {
    label: 'Dev UI Info',
    description: 'Developer UI overlay data',
    category: 'visuals',
    icon: 'bug_report',
    readonly: true,
    hidden: true,
    type: ParamType.INT,
  },
  ChevronInfo: {
    label: 'Chevron Info',
    description: 'Lead vehicle distance info',
    category: 'visuals',
    icon: 'directions_car',
    readonly: true,
    hidden: true,
    type: ParamType.INT,
  },
  ShowTurnSignals: { label: 'Show Turn Signals', description: 'Visualize turn signals', category: 'visuals', icon: 'flash_on', type: ParamType.BOOL },
  IsDriverViewEnabled: { label: 'Driver View', description: 'Show driver monitoring camera', category: 'visuals', icon: 'person', type: ParamType.BOOL },
  HideVEgoUI: { label: 'Hide Speed UI', description: 'Hide velocity readout', category: 'visuals', icon: 'visibility_off', type: ParamType.BOOL },
  ShowDebugInfo: {
    label: 'Show Debug Info',
    description: 'Display developer metrics',
    category: 'visuals',
    icon: 'bug_report',
    advanced: true,
    type: ParamType.BOOL,
  },
  LeadDepartAlert: {
    label: 'Lead Depart Alert',
    description: 'Alert when lead car moves',
    category: 'visuals',
    icon: 'departure_board',
    type: ParamType.BOOL,
  },
  TrueVEgoUI: { label: 'True Speed UI', description: 'Show raw vehicle speed', category: 'visuals', icon: 'speedometer', type: ParamType.BOOL },
  ApiCache_DriveStats: {
    label: 'API Cache: Drive Stats',
    description: 'Drive stats cache',
    category: 'developer',
    icon: 'cached',
    advanced: true,
    readonly: true,
    hidden: true,
    type: ParamType.JSON,
  },
  ApiCache_Device: {
    label: 'API Cache: Device',
    description: 'Device info cache',
    category: 'developer',
    icon: 'cached',
    advanced: true,
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  ApiCache_NavDestinations: {
    label: 'API Cache: Nav Destinations',
    description: 'Navigation cache',
    category: 'developer',
    icon: 'cached',
    advanced: true,
    readonly: true,
    hidden: true,
    type: ParamType.JSON,
  },
  AthenadPid: {
    label: 'Athena PID',
    description: 'Athena process ID',
    category: 'developer',
    icon: 'device_hub',
    readonly: true,
    hidden: true,
    type: ParamType.INT,
  },
  BootCount: {
    label: 'Boot Count',
    description: 'Number of boots',
    category: 'developer',
    icon: 'counter_1',
    advanced: true,
    readonly: true,
    type: ParamType.INT,
  },
  CalibrationParams: {
    label: 'Calibration Params',
    description: 'Camera calibration data',
    category: 'developer',
    icon: 'camera',
    readonly: true,
    hidden: true,
    type: ParamType.BYTES,
  },
  CarBatteryCapacity: {
    label: 'Car Battery Capacity',
    description: 'Battery size in kWh',
    category: 'developer',
    icon: 'battery_5_bar',
    advanced: true,
    readonly: true,
    type: ParamType.INT,
  },
  CarParams: {
    label: 'Car Params',
    description: 'Vehicle parameters',
    category: 'developer',
    icon: 'directions_car',
    readonly: true,
    hidden: true,
    type: ParamType.BYTES,
  },
  CarParamsCache: {
    label: 'Car Params Cache',
    description: 'Cached vehicle params',
    category: 'developer',
    icon: 'cached',
    readonly: true,
    hidden: true,
    type: ParamType.BYTES,
  },
  CarVin: {
    label: 'Car VIN',
    description: 'Vehicle identification',
    category: 'developer',
    icon: 'fingerprint',
    advanced: true,
    readonly: true,
    type: ParamType.STRING,
  },
  CompletedTrainingVersion: {
    label: 'Training Version',
    description: 'Last completed training',
    category: 'developer',
    icon: 'model_training',
    advanced: true,
    readonly: true,
    type: ParamType.STRING,
  },
  ControlsReady: {
    label: 'Controls Ready',
    description: 'System ready status',
    category: 'developer',
    icon: 'check',
    readonly: true,
    hidden: true,
    type: ParamType.BOOL,
  },
  CurrentRoute: {
    label: 'Current Route',
    description: 'Active drive route',
    category: 'developer',
    icon: 'route',
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  IMEI: { label: 'IMEI', description: 'Cellular modem ID', category: 'developer', icon: 'sim_card', advanced: true, readonly: true, type: ParamType.STRING },
  InstallDate: {
    label: 'Install Date',
    description: 'Installation timestamp',
    category: 'developer',
    icon: 'calendar_today',
    advanced: true,
    readonly: true,
    type: ParamType.TIME,
  },
  IsEngaged: {
    label: 'Is Engaged',
    description: 'Currently engaged',
    category: 'developer',
    icon: 'toggle_on',
    readonly: true,
    hidden: true,
    type: ParamType.BOOL,
  },
  IsFcwEnabled: {
    label: 'FCW Enabled',
    description: 'Forward collision warning',
    category: 'developer',
    icon: 'car_crash',
    advanced: true,
    readonly: true,
    type: ParamType.BOOL,
  },
  IsOffroad: {
    label: 'Is Offroad',
    description: 'Not currently driving',
    category: 'developer',
    icon: 'directions_car',
    readonly: true,
    hidden: true,
    type: ParamType.BOOL,
  },
  IsOnroad: {
    label: 'Is Onroad',
    description: 'Currently driving',
    category: 'developer',
    icon: 'directions_car',
    readonly: true,
    hidden: true,
    type: ParamType.BOOL,
  },
  IsReleaseBranch: {
    label: 'Is Release Branch',
    description: 'On release software',
    category: 'developer',
    icon: 'commit',
    readonly: true,
    hidden: true,
    type: ParamType.BOOL,
  },
  IsTestedBranch: {
    label: 'Is Tested Branch',
    description: 'On tested software',
    category: 'developer',
    icon: 'commit',
    readonly: true,
    hidden: true,
    type: ParamType.BOOL,
  },
  IsUpdateAvailable: {
    label: 'Update Available',
    description: 'Update pending',
    category: 'developer',
    icon: 'update',
    readonly: true,
    hidden: true,
    type: ParamType.BOOL,
  },
  LastAthenaPingTime: {
    label: 'Last Athena Ping',
    description: 'Last server contact',
    category: 'developer',
    icon: 'schedule',
    readonly: true,
    hidden: true,
    type: ParamType.INT,
  },
  LastGPSPosition: {
    label: 'Last GPS Position',
    description: 'GPS coordinates',
    category: 'developer',
    icon: 'gps_fixed',
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  LastOffroadStatusPacket: {
    label: 'Last Offroad Packet',
    description: 'Last status update',
    category: 'developer',
    icon: 'schedule',
    readonly: true,
    hidden: true,
    type: ParamType.JSON,
  },
  LastUpdateException: {
    label: 'Last Update Exception',
    description: 'Update error info',
    category: 'developer',
    icon: 'error',
    advanced: true,
    readonly: true,
    type: ParamType.STRING,
  },
  LastUpdateTime: {
    label: 'Last Update Time',
    description: 'Last update timestamp',
    category: 'developer',
    icon: 'schedule',
    advanced: true,
    readonly: true,
    type: ParamType.TIME,
  },
  LiveParameters: {
    label: 'Live Parameters',
    description: 'Runtime parameters',
    category: 'developer',
    icon: 'tune',
    readonly: true,
    hidden: true,
    type: ParamType.JSON,
  },
  Offroad_BadNvme: {
    label: 'Offroad: Bad NVMe',
    description: 'Storage error',
    category: 'developer',
    icon: 'storage',
    readonly: true,
    hidden: true,
    type: ParamType.JSON,
  },
  Offroad_CarUnrecognized: {
    label: 'Offroad: Car Unrecognized',
    description: 'Unknown vehicle',
    category: 'developer',
    icon: 'help',
    readonly: true,
    hidden: true,
    type: ParamType.JSON,
  },
  Offroad_ConnectivityNeeded: {
    label: 'Offroad: Connectivity Needed',
    description: 'Internet required',
    category: 'developer',
    icon: 'wifi',
    readonly: true,
    hidden: true,
    type: ParamType.JSON,
  },
  Offroad_InvalidTime: {
    label: 'Offroad: Invalid Time',
    description: 'Time sync error',
    category: 'developer',
    icon: 'schedule',
    readonly: true,
    hidden: true,
    type: ParamType.JSON,
  },
  Offroad_IsTakingSnapshot: {
    label: 'Offroad: Taking Snapshot',
    description: 'Snapshot in progress',
    category: 'developer',
    icon: 'photo_camera',
    readonly: true,
    hidden: true,
    type: ParamType.JSON,
  },
  Offroad_NeosUpdate: {
    label: 'Offroad: NEOS Update',
    description: 'OS update required',
    category: 'developer',
    icon: 'update',
    readonly: true,
    hidden: true,
    type: ParamType.JSON,
  },
  Offroad_NoFirmware: {
    label: 'Offroad: No Firmware',
    description: 'Firmware missing',
    category: 'developer',
    icon: 'error',
    readonly: true,
    hidden: true,
    type: ParamType.JSON,
  },
  Offroad_StorageMissing: {
    label: 'Offroad: Storage Missing',
    description: 'Storage not found',
    category: 'developer',
    icon: 'storage',
    readonly: true,
    hidden: true,
    type: ParamType.JSON,
  },
  Offroad_TemperatureTooHigh: {
    label: 'Offroad: Temperature High',
    description: 'Overheating',
    category: 'developer',
    icon: 'thermostat',
    readonly: true,
    hidden: true,
    type: ParamType.JSON,
  },
  Offroad_UnofficialHardware: {
    label: 'Offroad: Unofficial Hardware',
    description: 'Unsupported device',
    category: 'developer',
    icon: 'hardware',
    readonly: true,
    hidden: true,
    type: ParamType.JSON,
  },
  Offroad_UpdateFailed: {
    label: 'Offroad: Update Failed',
    description: 'Update error',
    category: 'developer',
    icon: 'error',
    readonly: true,
    hidden: true,
    type: ParamType.JSON,
  },
  Passive: { label: 'Passive', description: 'Passive mode', category: 'developer', icon: 'toggle_on', readonly: true, hidden: true, type: ParamType.BOOL },
  PrimeRedirected: {
    label: 'Prime Redirected',
    description: 'Prime redirect status',
    category: 'developer',
    icon: 'link',
    readonly: true,
    hidden: true,
    type: ParamType.BOOL,
  },
  PrimeType: {
    label: 'Prime Type',
    description: 'Prime subscription type',
    category: 'developer',
    icon: 'star',
    readonly: true,
    hidden: true,
    type: ParamType.INT,
  },
  SnoozeUpdate: {
    label: 'Snooze Update',
    description: 'Update snooze timer',
    category: 'developer',
    icon: 'timer',
    readonly: true,
    hidden: true,
    type: ParamType.BOOL,
  },
  SshEnabled: { label: 'Enable SSH', description: 'SSH access enabled', category: 'developer', icon: 'terminal', advanced: true, type: ParamType.BOOL },
  TermsVersion: {
    label: 'Terms Version',
    description: 'Accepted terms version',
    category: 'developer',
    icon: 'description',
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  TrainingVersion: {
    label: 'Training Version',
    description: 'Training software version',
    category: 'developer',
    icon: 'model_training',
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  UpdateAvailable: {
    label: 'Update Available',
    description: 'Update ready',
    category: 'developer',
    icon: 'update',
    advanced: true,
    readonly: true,
    type: ParamType.BOOL,
  },
  UpdateFailedCount: {
    label: 'Update Failed Count',
    description: 'Failed update attempts',
    category: 'developer',
    icon: 'error',
    advanced: true,
    readonly: true,
    type: ParamType.INT,
  },
  UpdaterAvailableBranches: {
    label: 'Available Branches',
    description: 'Update branches',
    category: 'developer',
    icon: 'commit',
    advanced: true,
    readonly: true,
    type: ParamType.STRING,
  },
  UpdaterCurrentDescription: {
    label: 'Current Description',
    description: 'Current branch info',
    category: 'developer',
    icon: 'description',
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  UpdaterCurrentReleaseNotes: {
    label: 'Current Release Notes',
    description: 'Release notes',
    category: 'developer',
    icon: 'description',
    readonly: true,
    hidden: true,
    type: ParamType.BYTES,
  },
  UpdaterFetchAvailable: {
    label: 'Updater Fetch Available',
    description: 'Update check ready',
    category: 'developer',
    icon: 'download',
    readonly: true,
    hidden: true,
    type: ParamType.BOOL,
  },
  UpdaterNewDescription: {
    label: 'New Description',
    description: 'New version info',
    category: 'developer',
    icon: 'description',
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  UpdaterNewReleaseNotes: {
    label: 'New Release Notes',
    description: 'New release notes',
    category: 'developer',
    icon: 'description',
    readonly: true,
    hidden: true,
    type: ParamType.BYTES,
  },
  UpdaterState: {
    label: 'Updater State',
    description: 'Update system state',
    category: 'developer',
    icon: 'update',
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  UpdaterTargetBranch: {
    label: 'Target Branch',
    description: 'Update target branch',
    category: 'developer',
    icon: 'commit',
    advanced: true,
    readonly: true,
    type: ParamType.STRING,
  },
  LagdToggleDelay: {
    label: 'LAQD Toggle Delay',
    description: 'Delay for LAQD toggle',
    category: 'developer',
    icon: 'timer',
    advanced: true,
    type: ParamType.FLOAT,
  },
  LagdToggle: {
    label: 'LAQD Toggle',
    description: 'Lightweight AQD Toggle',
    category: 'developer',
    icon: 'toggle_on',
    advanced: true,
    type: ParamType.BOOL,
  },
  ModelManager_Favs: {
    label: 'Model Favorites',
    description: 'Favorite drive models',
    category: 'developer',
    icon: 'star',
    advanced: true,
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  ModelManager_ActiveBundle: {
    label: 'Active Model Bundle',
    description: 'Currently active model',
    category: 'developer',
    icon: 'model_training',
    advanced: true,
    readonly: true,
    type: ParamType.JSON,
  },
  ShowAdvancedControls: {
    label: 'Show Advanced Controls',
    description: 'Unlock advanced settings',
    category: 'developer',
    icon: 'settings',
    advanced: true,
    type: ParamType.BOOL,
  },
  QuickBootToggle: { label: 'Quick Boot', description: 'Enable quick boot', category: 'developer', icon: 'bolt', advanced: true, type: ParamType.BOOL },
  ModelManager_ModelsCache: {
    label: 'Model Cache',
    description: 'Cached model list',
    category: 'developer',
    icon: 'cached',
    readonly: true,
    hidden: true,
    type: ParamType.JSON,
  },
  Offroad_TiciSupport: {
    label: 'TiCi Support',
    description: 'TiCi hardware support status',
    category: 'developer',
    icon: 'hardware',
    readonly: true,
    hidden: true,
    type: ParamType.JSON,
  },
  IsReleaseSpBranch: {
    label: 'SP Release Branch',
    description: 'On Sunnypilot release branch',
    category: 'developer',
    icon: 'commit',
    readonly: true,
    hidden: true,
    type: ParamType.BOOL,
  },
  SunnylinkEnabled: {
    label: 'sunnylink Enabled',
    description: 'Enable sunnylink services',
    category: 'developer',
    icon: 'cloud_sync',
    hidden: true,
    type: ParamType.BOOL,
  },
  EnableCopyparty: {
    label: 'Enable File Server',
    description: 'Start Copyparty file server',
    category: 'developer',
    icon: 'folder',
    advanced: true,
    type: ParamType.BOOL,
  },
  CarParamsSPCache: {
    label: 'SP Car Params Cache',
    description: 'Cached Sunnypilot car params',
    category: 'developer',
    icon: 'cached',
    readonly: true,
    hidden: true,
    type: ParamType.BYTES,
  },
  CarParamsSP: {
    label: 'SP Car Params',
    description: 'Sunnypilot vehicle parameters',
    category: 'developer',
    icon: 'directions_car',
    readonly: true,
    hidden: true,
    type: ParamType.BYTES,
  },
  ModelRunnerTypeCache: {
    label: 'Model Runner Type',
    description: 'Inference engine type',
    category: 'developer',
    icon: 'model_training',
    readonly: true,
    hidden: true,
    type: ParamType.INT,
  },
  OnroadCycleRequested: {
    label: 'Onroad Cycle',
    description: 'Cycle start requested',
    category: 'developer',
    icon: 'autorenew',
    readonly: true,
    hidden: true,
    type: ParamType.BOOL,
  },
  GithubRunnerSufficientVoltage: {
    label: 'Runner Voltage Check',
    description: 'Check voltage for GitHub runner',
    category: 'developer',
    icon: 'bolt',
    advanced: true,
    type: ParamType.BOOL,
  },
  CameraDebugExpGain: {
    label: 'Cam Debug Gain',
    description: 'Camera exposure gain',
    category: 'developer',
    icon: 'camera',
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  ApiCache_FirehoseStats: {
    label: 'Firehose Stats',
    description: 'Cached streaming stats',
    category: 'developer',
    icon: 'cached',
    readonly: true,
    hidden: true,
    type: ParamType.JSON,
  },
  JoystickDebugMode: {
    label: 'Joystick Debug',
    description: 'Enable joystick debugging',
    category: 'developer',
    icon: 'joystick',
    advanced: true,
    type: ParamType.BOOL,
  },
  EnableWebRTC: {
    label: 'Enable WebRTC',
    description: 'Allow remote live streaming',
    category: 'developer',
    icon: 'live_tv',
    advanced: true,
    type: ParamType.BOOL,
  },
  ModelManager_LastSyncTime: {
    label: 'Model Sync Time',
    description: 'Last model list sync',
    category: 'developer',
    icon: 'schedule',
    readonly: true,
    hidden: true,
    type: ParamType.INT,
  },
  IsDevelopmentBranch: {
    label: 'Dev Branch',
    description: 'On development channel',
    category: 'developer',
    icon: 'commit',
    readonly: true,
    hidden: true,
    type: ParamType.BOOL,
  },
  AthenadUploadQueue: {
    label: 'Upload Queue',
    description: 'Files queued for upload',
    category: 'developer',
    icon: 'queue',
    readonly: true,
    hidden: true,
    type: ParamType.JSON,
  },
  AssistNowToken: {
    label: 'AssistNow Token',
    description: 'GPS assist token',
    category: 'developer',
    icon: 'token',
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  CarParamsPrevRoute: {
    label: 'Previous Route Params',
    description: 'Params from previous route',
    category: 'developer',
    icon: 'route',
    readonly: true,
    hidden: true,
    type: ParamType.BYTES,
  },
  CarPlatformBundle: {
    label: 'Car Platform Bundle',
    description: 'Platform specific code',
    category: 'developer',
    icon: 'directions_car',
    readonly: true,
    hidden: true,
    type: ParamType.JSON,
  },
  AdbEnabled: { label: 'ADB Enabled', description: 'Android Debug Bridge', category: 'developer', icon: 'usb', advanced: true, type: ParamType.BOOL },
  ObdMultiplexingChanged: {
    label: 'OBD Multiplex Changed',
    description: 'Multiplexing setting changed',
    category: 'developer',
    icon: 'cable',
    readonly: true,
    hidden: true,
    type: ParamType.BOOL,
  },
  EnableSunnylinkUploader: {
    label: 'sunnylink Uploader',
    description: 'Upload drives to sunnylink',
    category: 'developer',
    icon: 'cloud_upload',
    type: ParamType.BOOL,
  },
  CameraDebugExpTime: {
    label: 'Cam Debug Time',
    description: 'Camera exposure time',
    category: 'developer',
    icon: 'camera',
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  FirmwareQueryDone: {
    label: 'Firmware Query Done',
    description: 'Firmware check complete',
    category: 'developer',
    icon: 'check',
    readonly: true,
    hidden: true,
    type: ParamType.BOOL,
  },
  ModelManager_DownloadIndex: {
    label: 'Model Download Index',
    description: 'Download queue index',
    category: 'developer',
    icon: 'download',
    readonly: true,
    hidden: true,
    type: ParamType.INT,
  },
  ModelManager_ClearCache: {
    label: 'Clear Model Cache',
    description: 'Delete downloaded models',
    category: 'developer',
    icon: 'delete',
    advanced: true,
    type: ParamType.BOOL,
  },
  CurrentBootlog: {
    label: 'Current Bootlog',
    description: 'Log of current boot',
    category: 'developer',
    icon: 'description',
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  Offroad_ExcessiveActuation: {
    label: 'Excessive Actuation',
    description: 'Controls saturation detected',
    category: 'developer',
    icon: 'warning',
    readonly: true,
    hidden: true,
    type: ParamType.JSON,
  },
  LastManagerExitReason: {
    label: 'Exit Reason',
    description: 'Reason for last process exit',
    category: 'developer',
    icon: 'exit_to_app',
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  CarParamsSPPersistent: {
    label: 'Car Params SP Persist',
    description: 'Persistent SP params',
    category: 'developer',
    icon: 'directions_car',
    readonly: true,
    hidden: true,
    type: ParamType.BYTES,
  },
  SecOCKey: { label: 'SecOC Key', description: 'Security key', category: 'developer', icon: 'security', readonly: true, hidden: true, type: ParamType.STRING },
  LastPowerDropDetected: {
    label: 'Power Drop',
    description: 'Last power drop event',
    category: 'developer',
    icon: 'bolt',
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  OnroadUploads: {
    label: 'Onroad Uploads',
    description: 'Upload status',
    category: 'developer',
    icon: 'cloud_upload',
    readonly: true,
    hidden: true,
    type: ParamType.BOOL,
  },
  LiveParametersV2: {
    label: 'Live Parameters V2',
    description: 'Runtime vehicle params V2',
    category: 'developer',
    icon: 'tune',
    readonly: true,
    hidden: true,
    type: ParamType.BYTES,
  },
  LastUpdateRouteCount: {
    label: 'Last Update Route Count',
    description: 'Routes since last update',
    category: 'developer',
    icon: 'counter_1',
    readonly: true,
    hidden: true,
    type: ParamType.INT,
  },
  LastUpdateUptimeOnroad: {
    label: 'Last Update Uptime',
    description: 'Driving time since update',
    category: 'developer',
    icon: 'timer',
    readonly: true,
    hidden: true,
    type: ParamType.FLOAT,
  },
  LagdValueCache: {
    label: 'LAQD Value Cache',
    description: 'Cached LAQD values',
    category: 'developer',
    icon: 'cached',
    readonly: true,
    hidden: true,
    type: ParamType.FLOAT,
  },
  EnableGithubRunner: {
    label: 'GitHub Runner',
    description: 'Enable CI/CD runner',
    category: 'developer',
    icon: 'build',
    advanced: true,
    type: ParamType.BOOL,
  },
  LiveDelay: {
    label: 'Live Delay',
    description: 'Communication delay',
    category: 'developer',
    icon: 'timer',
    readonly: true,
    hidden: true,
    type: ParamType.BYTES,
  },
  LocationFilterInitialState: {
    label: 'Loc Filter Init',
    description: 'Location filter state',
    category: 'developer',
    icon: 'gps_fixed',
    readonly: true,
    hidden: true,
    type: ParamType.BYTES,
  },
  PandaHeartbeatLost: {
    label: 'Panda Heartbeat Lost',
    description: 'Comms loss status',
    category: 'developer',
    icon: 'error',
    readonly: true,
    hidden: true,
    type: ParamType.BOOL,
  },
  Offroad_ConnectivityNeededPrompt: {
    label: 'Conn Needed Prompt',
    description: 'Prompt for internet',
    category: 'developer',
    icon: 'wifi',
    readonly: true,
    hidden: true,
    type: ParamType.JSON,
  },
  Offroad_Recalibration: {
    label: 'Recalibration',
    description: 'Recalibration required',
    category: 'developer',
    icon: 'camera',
    readonly: true,
    hidden: true,
    type: ParamType.JSON,
  },
  Offroad_UnregisteredHardware: {
    label: 'Unregistered',
    description: 'Device not registered',
    category: 'developer',
    icon: 'error',
    readonly: true,
    hidden: true,
    type: ParamType.JSON,
  },
  LastGPSPositionLLK: {
    label: 'Last GPS LLK',
    description: 'Last precise GPS loc',
    category: 'developer',
    icon: 'gps_fixed',
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  ObdMultiplexingEnabled: {
    label: 'OBD Multiplexing',
    description: 'Enable OBD multiplexing',
    category: 'developer',
    icon: 'cable',
    advanced: true,
    type: ParamType.BOOL,
  },
  Offroad_DriverMonitoringUncertain: {
    label: 'DM Uncertain',
    description: 'Driver monitoring checking',
    category: 'developer',
    icon: 'person',
    readonly: true,
    hidden: true,
    type: ParamType.JSON,
  },
  PandaSomResetTriggered: {
    label: 'Panda Reset Triggered',
    description: 'Reset trigger status',
    category: 'developer',
    icon: 'restart_alt',
    readonly: true,
    hidden: true,
    type: ParamType.BOOL,
  },
  PandaSignatures: {
    label: 'Panda Signatures',
    description: 'Firmware signatures',
    category: 'developer',
    icon: 'security',
    readonly: true,
    hidden: true,
    type: ParamType.BYTES,
  },
  UbloxAvailable: {
    label: 'Ublox GPS Available',
    description: 'GPS hardware status',
    category: 'developer',
    icon: 'gps_fixed',
    readonly: true,
    hidden: true,
    type: ParamType.BOOL,
  },
  CarParamsPersistent: {
    label: 'Car Params Persistent',
    description: 'Persistent vehicle params',
    category: 'developer',
    icon: 'directions_car',
    readonly: true,
    hidden: true,
    type: ParamType.BYTES,
  },
  IsTakingSnapshot: {
    label: 'Snapshotting',
    description: 'Camera capturing',
    category: 'developer',
    icon: 'photo_camera',
    readonly: true,
    hidden: true,
    type: ParamType.BOOL,
  },
  NavDestination: {
    label: 'Nav Destination',
    description: 'Navigation target',
    category: 'other',
    icon: 'place',
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  NavSettingLeftSide: {
    label: 'Nav Left Side',
    description: 'Left-side navigation',
    category: 'other',
    icon: 'swap_horiz',
    advanced: true,
    hidden: true,
    type: ParamType.BOOL,
  },
  NavSettingTime24h: {
    label: 'Nav 24h Time',
    description: '24-hour time format',
    category: 'other',
    icon: 'schedule',
    advanced: true,
    hidden: true,
    type: ParamType.BOOL,
  },
  NavdRender: {
    label: 'Nav Render',
    description: 'Navigation rendering',
    category: 'other',
    icon: 'map',
    advanced: true,
    hidden: true,
    type: ParamType.BOOL,
  },
  OsmStateName: {
    label: 'State Code',
    description: 'Current OSM state code',
    category: 'other',
    icon: 'place',
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  OsmLocationTitle: {
    label: 'Location Title',
    description: 'Current location title',
    category: 'other',
    icon: 'place',
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  OsmLocationName: {
    label: 'Location Name',
    description: 'Current location details',
    category: 'other',
    icon: 'place',
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  OSMDownloadProgress: {
    label: 'Map Download Progress',
    description: 'Map download status',
    category: 'other',
    icon: 'cloud_download',
    readonly: true,
    hidden: true,
    type: ParamType.JSON,
  },
  OSMDownloadLocations: {
    label: 'Map Download Locations',
    description: 'Queued map downloads',
    category: 'other',
    icon: 'cloud_download',
    readonly: true,
    hidden: true,
    type: ParamType.JSON,
  },
  OsmDownloadedDate: {
    label: 'Map Data Date',
    description: 'Date of downloaded maps',
    category: 'other',
    icon: 'calendar_today',
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  Offroad_OSMUpdateRequired: {
    label: 'Map Update Required',
    description: 'OSM maps need update',
    category: 'other',
    icon: 'update',
    readonly: true,
    hidden: true,
    type: ParamType.JSON,
  },
  MapdVersion: {
    label: 'Mapd Version',
    description: 'Map daemon version',
    category: 'other',
    icon: 'info',
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  SunnylinkTempFault: {
    label: 'sunnylink Fault',
    description: 'Temporary connection fault',
    category: 'other',
    icon: 'error',
    readonly: true,
    hidden: true,
    type: ParamType.BOOL,
  },
  SunnylinkCache_Users: {
    label: 'sunnylink User Cache',
    description: 'Cached user data',
    category: 'other',
    icon: 'group',
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  SunnylinkCache_Roles: {
    label: 'sunnylink Role Cache',
    description: 'Cached role data',
    category: 'other',
    icon: 'badge',
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  SunnylinkDongleId: {
    label: 'sunnylink ID',
    description: 'sunnylink device identifier',
    category: 'other',
    icon: 'fingerprint',
    readonly: true,
    type: ParamType.STRING,
  },
  MapSpeedLimit: {
    label: 'Map Speed Limit',
    description: 'Current speed limit from map',
    category: 'other',
    icon: 'speed_limit',
    readonly: true,
    hidden: true,
    type: ParamType.FLOAT,
  },
  OSMDownloadBounds: {
    label: 'Map Download Bounds',
    description: 'Map area boundaries',
    category: 'other',
    icon: 'map',
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  OsmDbUpdatesCheck: {
    label: 'Map Updates Check',
    description: 'Last map update check',
    category: 'other',
    icon: 'update',
    readonly: true,
    hidden: true,
    type: ParamType.BOOL,
  },
  AthenadRecentlyViewedRoutes: {
    label: 'Recent Routes',
    description: 'Recently viewed routes cache',
    category: 'other',
    icon: 'route',
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  OsmLocationUrl: {
    label: 'Location URL',
    description: 'OSM Location Link',
    category: 'other',
    icon: 'link',
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  AccessToken: {
    label: 'Access Token',
    description: 'API Access Token',
    category: 'other',
    icon: 'token',
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  SunnylinkdPid: {
    label: 'sunnylink PID',
    description: 'sunnylink process ID',
    category: 'other',
    icon: 'device_hub',
    readonly: true,
    hidden: true,
    type: ParamType.INT,
  },
  OsmLocal: { label: 'Local OSM', description: 'Use local OSM server', category: 'other', icon: 'map', advanced: true, hidden: true, type: ParamType.BOOL },
  MapTargetVelocities: {
    label: 'Map Target Velocities',
    description: 'Map-based velocity targets',
    category: 'other',
    icon: 'speed',
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  OsmWayTest: {
    label: 'OSM Way Test',
    description: 'Debug OSM way query',
    category: 'other',
    icon: 'bug_report',
    advanced: true,
    hidden: true,
    type: ParamType.STRING,
  },
  NextMapSpeedLimit: {
    label: 'Next Map Speed',
    description: 'Upcoming speed limit',
    category: 'other',
    icon: 'speed_limit',
    readonly: true,
    hidden: true,
    type: ParamType.JSON,
  },
  OsmStateTitle: {
    label: 'State Region',
    description: 'Current OSM region',
    category: 'other',
    icon: 'place',
    readonly: true,
    hidden: true,
    type: ParamType.STRING,
  },
  LastSunnylinkPingTime: {
    label: 'LastSunnylinkPingTime',
    description: 'Unknown setting from device',
    category: 'other',
    icon: 'schedule',
    hidden: true,
    type: ParamType.INT,
  },
  WebRTCOnline: { label: '', description: '', category: 'other', icon: 'live_tv', hidden: true, type: ParamType.BOOL },
  LastAgnosPowerMonitorShutdown: { label: '', description: '', category: 'other', icon: 'power_settings_new', hidden: true, type: ParamType.STRING },
  CarList: { label: '', description: '', category: 'other', icon: 'directions_car', hidden: true, type: ParamType.JSON },
}
